name: deploy-gh-page

on:
  push:
    branches:
      - "3.9"

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install gettext

      - name: Build
        run: make

      - name: Deploy to gh page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ../cpython/Doc/build/html
          CLEAN: true
