name: python-3.12-sync-with-cpython

on:
  push:
    branches:
      - "3.12"
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      VERSION: "3.12"
      BRANCH: "cron/sync/3.12"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.VERSION }}

      - name: Get the changes on branch (if exists)
        continue-on-error: true
        run: |
          git fetch origin ${{ env.BRANCH }}:${{ env.BRANCH }}
          git reset --hard ${{ env.BRANCH }}

      - name: Set env
        run: echo "LATEST_COMMIT_ID=$(git ls-remote https://github.com/python/CPython.git $VERSION | head -c 8)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: sudo apt-get install gettext

      - name: Sync with CPython
        run: make clone && make merge && make rm_cpython

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: sync with cpython ${{ env.LATEST_COMMIT_ID }}
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          base: ${{ env.VERSION }}
          branch: ${{ env.BRANCH }}
          delete-branch: false
          title: 'Sync with CPython ${{ env.VERSION }}'
          body: |
            Sync with CPython ${{ env.VERSION }}
          draft: true
          labels: |
            sync-cpython
            automation
          
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"